language: php

php:
  - "5.6"
  - hhvm

before_script:
  - composer install --prefer-dist --dev

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script: ./vendor/phpunit/phpunit/phpunit.php --stderr

notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
